== Basic expressions
An _expression_ produces a new value.

Keep in mind that some operators will occur _before_ others so you may need to _group_ expressions using round brackets (parentheses `()`).

=== String concatenation (joining)
[source,javascript]
----
"Hello" + "World" // produces "HelloWorld"

"Hello, " + "World" + "!" // produces "Hello, World!"
----

=== Basic arithmetic
[source,javascript]
----
3 + 2 // add: produces 5
3 - 2 // subtract: produces -1
3 * 2 // multiply: produces 6
  // '*' is called asterisk and is usually SHIFT+8 on keyboard
3 / 2 // divide: produces 1.5
  // '/' is called a forward-slash and found below '?' on keyboard
3 % 2 // modulo (whole-number remainder of divide): produces 1
----

Like in mathematics, multiplication/division occur before addition/subtraction, so use parentheses:

[source,javascript]
----
2 + 3 * 4 // == 2 + 12 == 14
(2 + 3) * 4 // == 5 * 4 == 20
----

=== Boolean expressions

The _and_ and _or_ operators take two boolean values (or expressions) and provide a new boolean value.

==== Boolean _and_
The "and" (`&&`) operator returns true only if both sides are true.

[source,javascript]
----
true && true    // true
true && false   // false
false && true   // false
false && false  // false
----

==== Boolean _or_
The "or" (`||`) operator returns true only if either or both sides are true.

[source,javascript]
----
true || true    // true
true || false   // true
false || true   // true
false || false  // false
----


=== Relational expressions

You often want to compare two different values, particularly _link:./variables.adoc[variables]_ so JavaScript provides some operators for that. These operators take two values/expressions (ideally numeric) and provide a new boolean value.

==== Equality and inequality

Use `===` (equal?) and `!==` (not equal?) to test for equality. For example:

[source,javascript]
----
"a" === "a" // true
"a" !== "b" // also true
"b" !== "b" // false
----

WARNING: The `=` operator is for _assigning variables_ and does not test whether two values are equal. 

WARNING: Like many languages, JavaScript also has a `==` operator (and `!=`). However, it can do very strange things, so avoid using it.


==== Greater/less than

Rather than testing whether two values are equal, we can test whether one is greater than the other. (This should really only be used with _numbers_ although JavaScript allows it on other data types!)

[source,javascript]
----
5 > 2 // true
2 > 5 // false
5 > 5 // false

5 < 2 // false
2 < 5 // true
5 < 5 // false

5 >= 2 // true
2 >= 5 // false
5 >= 5 // true - different from >

5 <= 2 // false
2 <= 5 // true
5 <= 5 // true - different from <
----